# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_categories_20170121_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.CharField(choices=[('Unapproved', 'Unapproved'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Unapproved', max_length=15),
        ),
    ]
