# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_logentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='organisation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logbook.Organisation'),
        ),
    ]
