# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 08:13
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group

def createGroups(apps, schema_editor):
    studentGroup, created = Group.objects.get_or_create(name='LBStudent')
    supervisorGroup, created = Group.objects.get_or_create(name='LBSupervisor')

class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_logbook_organisation'),
        ('auth', '__latest__')
    ]

    operations = [
        migrations.RunPython(createGroups)
    ]
