# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_userGroups_20170123_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=8),
        ),
    ]
