# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0005_logbook_name_slug'),
        ('logbook', '0006_organisation_code'),
    ]

    operations = [
    ]
