# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_merge_20170129_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='name_slug',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='category',
        ),
        migrations.AddField(
            model_name='logbook',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='logbook.Category'),
        ),
    ]
