# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_auto_20170202_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logbook.LogBook'),
        ),
    ]
