# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models

import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_auto_20170207_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbuser',
            name='activation_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='lbuser',
            name='key_expires',
            field=models.DateTimeField(datetime.datetime.now()+datetime.timedelta(days=7)),
        ),
    ]
