# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 16:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_auto_20170225_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logbook',
            name='finalised',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 0, 8, 52, 987147)),
        ),
    ]
