# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0011_auto_20170311_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='description',
        ),
        migrations.AddField(
            model_name='logbook',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 19, 18, 13, 166832)),
        ),
    ]
